### ISSUE TITLE
Added pip install for nilearn and scikit-learn

### ISSUE THREAD

**Issue by bcoffman** [ncullen93/mesh2nifti#1]
Had to remove  nibabel and nilearn from conda create at line 81 and added the following two lines at line 84:
$TARGET_DIR/miniconda2/envs/simnibs_env/bin/pip install nilearn
$TARGET_DIR/miniconda2/envs/simnibs_env/bin/pip install scikit-learn

**Comment by ncullen93** [comment]
fixed, thanks :)
